#
# GitHub Actions Workflow: Fully Automated Chrome Flatpak CI/CD
#
# Author: Senior Flatpak Packager & Security Analyst
#
# Description:
# This workflow automates the entire packaging lifecycle based on Git tags.
# 1. Checks for a new Chrome version that is not already tagged in the repo.
# 2. Updates all manifest dependencies.
# 3. Builds the Flatpak package.
# 4. If, and only if, the build is successful, it commits the updated manifest
#    to the 'main' branch and tags that commit with the Chrome version.
# 5. It then deploys the repository to the 'gh-pages' branch and creates a
#    separate 'deploy-<version>' tag pointing to the deployment commit.
#
name: 'Automated Chrome Flatpak CI/CD'

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 5 * * *' # Runs daily at 5 AM UTC

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.repo.outputs.version }}
      update: ${{ steps.check.outputs.update }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-tags: 'true'

      - name: "Fetch Chrome Debian Repository"
        id: repo
        run: |
          PACKAGE_INFO=$(curl -sL https://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages | awk 'BEGIN{RS=""} /Package: google-chrome-stable/{print}')
          VERSION=$(echo "$PACKAGE_INFO" | grep '^Version:' | awk '{print $2}')
          CHECKSUM=$(echo "$PACKAGE_INFO" | grep '^SHA256:' | awk '{print $2}')
          echo "Latest Chrome Version Found: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: "Check For Version Tag"
        id: check
        run: |
          VERSION=${{ steps.repo.outputs.version }}
          if git ls-remote --exit-code --tags origin ${VERSION}; then
            echo "Tag for version ${VERSION} already exists. No update needed."
            echo "update=false" >> $GITHUB_OUTPUT
          else
            echo "New version ${VERSION} detected. Proceeding with build."
            echo "update=true" >> $GITHUB_OUTPUT
          fi

  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    needs: check
    if: needs.check.outputs.update == 'true'
    permissions:
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          ref: main
          path: main

      - name: "Update Manifest"
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --edit-only /github/workspace/main/com.google.Chrome.yaml

      - name: 'Import GPG Key'
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: "Check GitHub Pages Branch"
        id: pages
        run: |
          if git -C main ls-remote --exit-code --branches origin gh-pages; then
            echo "GitHub Pages branch already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "flat_dir=gh-pages" >> $GITHUB_OUTPUT
          else
            echo "GitHub Pages branch doesn't exist."
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "flat_dir=flat" >> $GITHUB_OUTPUT
          fi

      - name: "Checkout GitHub Pages Repository For Update"
        if: steps.pages.outputs.exists == 'true'
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Checkout Repository For GitHub Pages Creation"
        if: steps.pages.outputs.exists == 'false'
        uses: actions/checkout@v5
        with:
          path: gh-pages

      - name: "Init GitHub Pages Repository"
        if: steps.pages.outputs.exists == 'false'
        run: |
          git -C gh-pages switch --orphan gh-pages
          cp main/.gitattributes gh-pages/
          git -C gh-pages lfs install
          git -C gh-pages lfs track "**/objects/**"

      - name: "Build Flatpak"
        run: |
          VERSION=${{ needs.check.outputs.version }}
          FLAT_DIR=${{ steps.pages.outputs.flat_dir }}
          flatpak-builder --repo="$FLAT_DIR" --force-clean --disable-rofiles-fuse \
            --subject="Update Chrome to ${VERSION}" build-dir main/com.google.Chrome.yaml

      - name: "Merge flat into gh-pages"
        if: steps.pages.outputs.exists == 'false'
        run: cp -a flat/. gh-pages

      - name: "Create / Update chrome.flatpakrepo"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          {
            echo "[Flatpak Repo]";
            echo "Title=Google Chrome (Unofficial)";
            echo "Url=${REPO_URL}";
            echo "GPGKey=$(gpg --export $GPG_KEY_ID | base64 | tr -d '\n')";
          } > "gh-pages/chrome.flatpakrepo"

      - name: "Sign Flatpak Repository Summary"
        run: flatpak build-update-repo --gpg-sign="$GPG_KEY_ID" --prune gh-pages

      - name: "Configure Git For Deployment"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Publish GitHub Pages Repositry"
        run: |
          VERSION=${{ needs.check.outputs.version }}
          if [ -z "$(git -C gh-pages status --porcelain)" ]; then
            echo "✅ No changes to commit."
          else
            git -C gh-pages add .
            git -C gh-pages commit -m "Deploy Chrome version ${VERSION}"
            git -C gh-pages push origin gh-pages
          fi
          git -C gh-pages tag "deploy-${VERSION}"
          git -C gh-pages push origin "deploy-${VERSION}"

      - name: "Commit Manifest And Tag Main Branch"
        run: |
          VERSION=${{ needs.check.outputs.version }}
          if [ -z "$(git -C main status --porcelain)" ]; then
            echo "✅ No changes to commit."
          else
            git -C main add com.google.Chrome.yaml com.google.Chrome.metainfo.xml
            git -C main commit -m "Update Chrome to version ${VERSION}"
            git -C main push
          fi
          git -C main tag "${VERSION}"
          git -C main push --tags
