#
# GitHub Actions Workflow: Fully Automated Chrome Flatpak CI/CD
#
# Author: Senior Flatpak Packager & Security Analyst
#
# Description:
# This workflow automates the entire packaging lifecycle based on Git tags.
# 1. Checks for a new Chrome version that is not already tagged in the repo.
# 2. Updates all manifest dependencies.
# 3. Builds the Flatpak package.
# 4. If, and only if, the build is successful, it commits the updated manifest
#    to the 'main' branch and tags that commit with the Chrome version.
# 5. It then deploys the repository to the 'gh-pages' branch and creates a
#    separate 'deploy-<version>' tag pointing to the deployment commit.
#
name: 'Automated Chrome Flatpak CI/CD'

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 5 * * *' # Runs daily at 5 AM UTC

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.repo.outputs.version }}
      update: ${{ steps.check.outputs.update }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          fetch-tags: 'true'

      - name: "Fetch Chrome Debian Repository"
        id: repo
        run: |
          PACKAGE_INFO=$(curl -sL https://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages | awk 'BEGIN{RS=""} /Package: google-chrome-stable/{print}')
          VERSION=$(echo "$PACKAGE_INFO" | grep '^Version:' | awk '{print $2}')
          CHECKSUM=$(echo "$PACKAGE_INFO" | grep '^SHA256:' | awk '{print $2}')
          echo "Latest Chrome Version Found: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: "Check For Version Tag"
        id: check
        run: |
          VERSION=${{ steps.repo.outputs.version }}
          if git ls-remote --exit-code --tags origin ${VERSION}; then
            echo "Tag for version ${VERSION} already exists. No update needed."
            echo "update=false" >> $GITHUB_OUTPUT
          else
            echo "New version ${VERSION} detected. Proceeding with build."
            echo "update=true" >> $GITHUB_OUTPUT
          fi

  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    needs: check
    if: needs.check.outputs.update == 'true'
    permissions:
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          path: main

      - name: "Update Manifest"
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: /github/workspace/main/com.google.Chrome.yaml

      - name: 'Import GPG Key'
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: "Build Flatpak"
        run: |
          VERSION=${{ needs.check.outputs.version }}
          flatpak-builder --repo=flat --force-clean --disable-rofiles-fuse \
            --subject="Update Chrome to ${VERSION}" build-dir main/com.google.Chrome.yaml

      - name: "Check GitHub Pages Branch"
        id: pages
        run: |
          if git -C main ls-remote --exit-code --branches origin gh-pages; then
            echo "GitHub Pages branch already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "GitHub Pages branch doesn't exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: "Checkout Repository for GitHub Pages Creation"
        if: steps.pages.outputs.exists == 'false'
        uses: actions/checkout@v5
        with:
          path: gh-pages

      - name: "Create GitHub Pages Repository"
        if: steps.pages.outputs.exists == 'false'
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          git -C gh-pages switch --orphan gh-pages
          cp -a repo/. gh-pages
          flatpak build-sign --gpg-sign="$GPG_KEY_ID" gh-pages

      - name: "Checkout GitHub Pages Repository For Update"
        if: steps.pages.outputs.exists == 'true'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Update GitHub Pages Repository"
        if: steps.pages.outputs.exists == 'true'
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: flatpak build-update-repo --gpg-sign="$GPG_KEY_ID" --prune gh-pages repo

      - name: "Sign GitHub Pages Repository Summary"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: ostree summary -u --gpg-sign="$GPG_KEY_ID" gh-pages

      - name: "Configure Git For Deployment"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Publish GitHub Pages Repositry"
        run: |
          git -C gh-pages add .
          git -C gh-pages commit -m "Deploy Chrome version ${VERSION}"
          git -C gh-pages tag "deploy-${VERSION}"
          git -C gh-pages push origin gh-pages
          git -C gh-pages push origin "deploy-${VERSION}"

      - name: "Commit Manifest And Tag Main Branch"
        run: |
          VERSION=${{ steps.repo.outputs.version }}
          git -C main add com.google.Chrome.yaml com.google.Chrome.metainfo.xml
          git -C main commit -m "Update Chrome to version ${VERSION}"
          git -C main tag "${VERSION}"
          git -C main push main
          git -C main push origin "${VERSION}"
